# Plugin coordinates
pluginGroup = com.marlzrana.heview
pluginVersion = 0.0.1
pluginSinceBuild = 242

# Target IntelliJ Platform (IC = IntelliJ IDEA Community)
platformType = IC
platformVersion = 2024.2.1

# Gradle
org.gradle.jvmargs = -Xmx2g -Dfile.encoding=UTF-8
org.gradle.caching = true

# The Kotlin stdlib is provided by the IntelliJ Platform at runtime — do not bundle it
kotlin.stdlib.default.dependency = false
